### A dummy protocol api for the testing purpose ###

class ProtocolContext():
    def __init__(self): ...
    def load_labware_from_definition(self, *args, **kwargs): ...
    def load_labware(self, *args, **kwargs): ...
    def load_instrument(self, *args, **kwargs): ...
    def delay(self, *args, **kwargs): ...